server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # nacos 服务注册中心地址
        server-addr: 129.211.93.117:1111
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口,加入被占用会自动从8719开始依次+1扫描,直到找到未被占用的端口
        port: 8719
      # 从nacos读取配置
      datasource:
        ds1:
          nacos:
            server-addr: 129.211.93.117:1111
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            dataType: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
