server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  # 采样值介于0到1之间,1 表示全部采集 一般为0.5
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf8&useSSL=false&useUnicode=true             # 数据库名称
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.ysy.springcloud.entities    # 所有Entity别名类所在包
  mapperLocations: classpath:mapper/**/*.xml                       # mapper映射文件
eureka:
  instance:
    prefer-ip-address: true
    instance-id: payment8001
    #Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限 ,单位为秒(默认是90秒),超时剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    # 默认 true 可省略
    register-with-eureka: true
    # 默认 true 可省略
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群
